print("File Handling") 
print("==========\n") 
 
"""Writing a file""" 
print("Writing a file") 
print("---------------") 
file1=open("student.txt",'w') 
file1.write("101 James 60 70 pass\n") 
file1.write("102 John 65 66 pass\n") 
print("Name of the file : ",file1.name) 
print("Opening mode : ",file1.mode) 
print("File closed : ",file1.closed) 
print("\n *****  Two students information are written in to the file  *****\n") 
file1.close() 
 
"""Reading a file""" 
print("Reading a file") 
print("----------------") 
file1=open("student.txt",'r') 
print("Name of the file : ",file1.name) 
print("Opening mode : ",file1.mode) 
print("File closed : ",file1.closed) 
print("student.txt : \n",file1.read()) 
file1.close() 
 
print("*****  Two students information are read from the file  *****\n") 
"""Opening a file in append mode""" 
print("Opening a file in append mode") 
print("-------------------------------------") 
file1=open("student.txt",'a') 
print("Name of the file : ",file1.name) 
print("Opening mode : ",file1.mode) 
print("File closed : ",file1.closed) 
file1.write("103 Robert 40 70 fail\n") 
file1.write("104 Williams 60 60 pass\n") 
file1=open("student.txt",'r') 
print("student.txt after writing in append mode : \n",file1.read()) 
print("*****  Additionally two students information are written at the end of the file  *****\n") 
file1.close() 
